DROP DATABASE IF EXISTS finviz;
CREATE DATABASE finviz;
USE finviz;
CREATE TABLE `findata` (
  `iddownload` varchar(45) DEFAULT '0',
  `ticker` varchar(10) NOT NULL,
  `date` datetime NOT NULL,
  `price` float DEFAULT NULL,
  `targetprice` float DEFAULT NULL,
  `volume` float DEFAULT NULL,
  `relvolume` float DEFAULT NULL,
  `rsi14` float DEFAULT NULL,
  `52whigh` float DEFAULT NULL,
  `52wlow` float DEFAULT NULL,
  `shortratio` float DEFAULT NULL,
  `shortfloat` float DEFAULT NULL,
  `instown` float DEFAULT NULL,
  `insttrans` float DEFAULT NULL,
  `insidown` float DEFAULT NULL,
  `insidtrans` float DEFAULT NULL,
  `profitmargin` float DEFAULT NULL,
  `debteq` float DEFAULT NULL,
  `peg` float DEFAULT NULL,
  `pe` float DEFAULT NULL,
  `forwardpe` float DEFAULT NULL,
  `pricetobook` float DEFAULT NULL,
  `booksh` float DEFAULT NULL,
  `cashsh` float DEFAULT NULL,
  `reco` float DEFAULT NULL,
  `dividendpercent` float DEFAULT NULL,
  `perfyear` float DEFAULT NULL,
  `perfhalfyear` float DEFAULT NULL,
  `employees` float DEFAULT NULL,
  `optionable` varchar(4) DEFAULT NULL,
  `shortable` varchar(4) DEFAULT NULL,
  `sector` varchar(100) DEFAULT NULL,
  `industry` varchar(100) DEFAULT NULL,
  `country` varchar(100) DEFAULT NULL,
  `lastinsiderpurchaseprice` float DEFAULT NULL,
  `lastinsiderpurchasevalue` float DEFAULT NULL,
  `lastinsidersaleprice` float DEFAULT NULL,
  `lastinsidersalevalue` float DEFAULT NULL,
  `lastinsiderpurchaseisbyowner` varchar(4) DEFAULT NULL,
  `lastinsidersaleisbyowner` varchar(4) DEFAULT NULL,
  `numrecentinsiderpurchases` float DEFAULT NULL,
  `numrecentinsidersales` float DEFAULT NULL,
  `numrecentdifferentinsiderpurchases` float DEFAULT NULL,
  `numrecentdifferentinsidersales` float DEFAULT NULL
) 

; select Host,User,Password from mysql.user; show variables;